name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./Backend-Automation-RE.sln

    - name: Build the solution
      run: dotnet build ./Backend-Automation-RE.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ./Backend-Automation-RE.sln --no-build --verbosity normal
